### ISSUE TITLE
Error: Slider was already initialized.

### ISSUE THREAD

**Issue by linearza** [kennethkalmer/ember-cli-nouislider#30] opened 2016-07-11 07:29 UTC
Getting this error when inserting multiple sliders on the same page.

Started looking into it this morning, and this issue might be related: https://github.com/leongersen/noUiSlider/issues/353

**Comment by linearza** [comment] 2016-07-11 09:01
It seems to fire the didInsertElement hook twice in each instance, not sure if its a case thats specific to our app but, a possible solution would be to check if the slider has been created before. Something like:

```
if (!this.get('slider')) {
  noUiSlider.create($this, properties);
}
```

If thats acceptable I can create a PR for it

**Comment by linearza** [comment] 2016-07-11 09:07
https://github.com/kennethkalmer/ember-cli-nouislider/pull/31

**Comment by kennethkalmer** [comment] 2016-07-11 21:52
Hmm, `didInsertElement` should not run twice. I might be doing something in there that causes it to re-run and will have to have a look. Can you confirm that `willDestroyElement` is run in between? Maybe the cleanup is inadequate...

Thanks for the PR.

In the meanwhile, which ember versions are you using if I want to try and reproduce it.

**Comment by kennethkalmer** [comment] 2017-02-27 19:40
Closing since we have #31 & #39 tackling this. Thanks for using the addon, and reporting an issue that helps make it better for everyone!

**Closed by kennethkalmer** 2017-02-27 19:40 UTC
